### ISSUE TITLE
no attribute 'addDirectoryField'

### ISSUE THREAD

**Issue by snehashis-roy** [LauLauThom/MaskFromRois-Fiji#6]
Hi,
I tried to install this plugin by copying the unzipped folder to my Fiji.app folder. I tried with both Fiji 1.53c and 2.2.0

This is the error message after drawing some ROIs, and the selecting Edit->Selection->Mask from ROI
```
File "Edit/Selection/Mask_from_Rois/Binary_(0-255)_mask(s)_from_Roi(s).py", line 27, in <module>
AttributeError: 'ij.gui.GenericDialog' object has no attribute 'addDirectoryField'

	at org.python.core.Py.AttributeError(Py.java:178)
	at org.python.core.PyObject.noAttributeError(PyObject.java:965)
	at org.python.core.PyObject.__getattr__(PyObject.java:959)
	at org.python.pycode._pyx0.f$0(Edit/Selection/Mask_from_Rois/Binary_(0-255)_mask(s)_from_Roi(s).py:127)
	at org.python.pycode._pyx0.call_function(Edit/Selection/Mask_from_Rois/Binary_(0-255)_mask(s)_from_Roi(s).py)
	at org.python.core.PyTableCode.call(PyTableCode.java:173)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1687)
	at org.python.core.__builtin__.eval(__builtin__.java:497)
	at org.python.core.__builtin__.eval(__builtin__.java:501)
	at org.python.util.PythonInterpreter.eval(PythonInterpreter.java:255)
	at org.python.jsr223.PyScriptEngine.eval(PyScriptEngine.java:57)
	at org.python.jsr223.PyScriptEngine.eval(PyScriptEngine.java:31)
	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
	at org.scijava.script.ScriptModule.run(ScriptModule.java:157)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:124)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:63)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:225)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
Is there an specific version of Fiji or python that is required?
Thank you.

**Comment by LauLauThom** [comment]
Hi there, sorry for the late reply,
A specific version of Fiji/python no, but of ImageJ it seems yes (I think min 1.53d) 😋
Can you let me know what is you current version of ImageJ (*Help > About ImageJ...*).
Then update the ImageJ version with *Help > Update ImageJ...* 
That should fix it ;)
